services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SeoBundle\Studio\Service\MetaDataServiceInterface: '@SeoBundle\Studio\Service\MetaDataService'
    SeoBundle\Studio\Service\MetaDataService: ~
